version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared_web:/usr/share/nginx/html
    networks:
      - web_network
    depends_on:
      - ftp

  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: ftp_server
    environment:
      PUBLICHOST: "127.0.0.1"
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: ftppass
      FTP_USER_HOME: /home/ftpuser
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - shared_web:/home/ftpuser/web
    networks:
      - web_network

volumes:
  shared_web:

networks:
  web_network:
    driver: bridge